#! /bin/bash
. /usr/lib/network/network

wvdial_up () {
  load_profile $1
  [[ -z "$WVDIAL_CONFIG" ]] && WVDIAL_CONFIG="/etc/wvdial.conf"
  [[ -z "$WVDIAL_PID_FILE" ]] && WVDIAL_PID_FILE="/var/run/wvdial-$1.pid"
  [[ -z "$WVDIAL_FLAGS" ]] && WVDIAL_FLAGS=""

  dtach -x $WVDIAL_PID_FILE wvdial -C $WVDIAL_CONFIG $WVDIAL_FLAGS $1

  if [[ $? -ne 0 ]]; then
    report_fail "WVDIAL connection failed"
    exit 1
  fi

  # Generate a new resolv.conf
  if [[ -n "$DNS" ]]; then
      [[ -e /etc/resolv.conf ]] && cp /etc/resolv.conf /tmp/wvdial-$1-resolv.conf
      : >/etc/resolv.conf
      [[ -n "$DOMAIN" ]] && echo "domain $DOMAIN"   >>/etc/resolv.conf
      [[ -n "$SEARCH" ]] && echo "search $SEARCH"   >>/etc/resolv.conf

      for dns in "${DNS[@]}"; do
        echo "nameserver $dns" >>/etc/resolv.conf
      done
  elif [[ -n "$DNS1" ]]; then # support older 'ethernet' syntax.
      [[ -e /etc/resolv.conf ]] && cp /etc/resolv.conf /tmp/wvdial-$1-resolv.conf
      : >/etc/resolv.conf
      [[ -n "$DOMAIN" ]] && echo "domain $DOMAIN"   >>/etc/resolv.conf
      [[ -n "$SEARCH" ]] && echo "search $SEARCH"   >>/etc/resolv.conf
      [[ -n "$DNS1" ]]   && echo "nameserver $DNS1" >>/etc/resolv.conf
      [[ -n "$DNS2" ]]   && echo "nameserver $DNS2" >>/etc/resolv.conf
  fi
}

wvdial_down() {
    load_profile $1
    [[ -z "$WVDIAL_PID_FILE" ]] && WVDIAL_PID_FILE="/var/run/openvpn-$1.pid"

    #kill $(head -1 $WVDIAL_PID_FILE) #trovare un modo per chiudere una sessione di dtach
    #rm $WVDIAL_PID_FILE

    # Restore an old resolv.conf
    if [[ -e /tmp/wvdial-$1-resolv.conf ]]; then
        mv -f /tmp/wvdial-$1-resolv.conf /etc/resolv.conf
    fi
}

wvdial_$1 $2
exit $?
